name: iOS Traceability Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  trace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Install Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.6'
          
      - name: Install OpenFastTrace
        run: |
          # Download the OpenFastTrace JAR file directly
          wget https://github.com/itsallcode/openfasttrace/releases/download/4.1.0/openfasttrace-cli-4.1.0-jar-with-dependencies.jar -O /tmp/openfasttrace-cli.jar
          
          # Create a simple shell script wrapper
          echo "#!/bin/sh" > /tmp/oft
          echo "java -jar /tmp/openfasttrace-cli.jar \"\$@\"" > /tmp/oft
          sudo mv /tmp/oft /usr/local/bin/oft
          sudo chmod +x /usr/local/bin/oft
          
          # Verify installation
          oft version
      
      - name: Run Traceability Analysis
        run: |
          # Import specifications from all source files and generate a tracing report
          echo "Analyzing traceability in iOS implementation..."
          
          # Debug: check that the oft script works
          which oft
          ls -la /usr/local/bin/oft
          cat /usr/local/bin/oft
          
          oft import -i . -o trace.xml
          oft report -i trace.xml -o verification-ios.md -f markdown
      
      - uses: actions/upload-artifact@v4
        with:
          name: ios-verification
          path: verification-ios.md 