name: iOS Traceability Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  trace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Install Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.6'
          
      - name: Install OpenFastTrace
        run: |
          # Clone the OpenFastTrace repository
          git clone https://github.com/itsallcode/openfasttrace.git
          cd openfasttrace
          
          # Build with Maven (skipping tests for speed)
          mvn clean install -DskipTests
          
          # Find the path to the JAR file
          OFT_JAR=$(find $(pwd) -name "openfasttrace-cli-*-jar-with-dependencies.jar" | head -n 1)
          echo "OFT_JAR=$OFT_JAR" >> $GITHUB_ENV
          
          # Create a simple shell script wrapper
          echo "#!/bin/sh
          java -jar $OFT_JAR \"\$@\"" > /tmp/oft
          sudo mv /tmp/oft /usr/local/bin/oft
          sudo chmod +x /usr/local/bin/oft
      
      - name: Run Traceability Analysis
        run: |
          # Import specifications from all source files and generate a tracing report
          echo "Analyzing traceability in iOS implementation..."
          
          # Debug: check that the oft script works
          which oft
          ls -la /usr/local/bin/oft
          cat /usr/local/bin/oft
          
          oft import -i . -o trace.xml
          oft report -i trace.xml -o verification-ios.md -f markdown
      
      - uses: actions/upload-artifact@v4
        with:
          name: ios-verification
          path: verification-ios.md 