name: iOS Traceability Analysis

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  trace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.6'
          
      - name: Install OpenFastTrace
        run: |
          # Download the OpenFastTrace JAR
          mkdir -p /tmp/oft
          cd /tmp/oft
          wget https://github.com/itsallcode/openfasttrace/releases/download/3.3.1/openfasttrace-3.3.1.jar
          
          # Make the OFT command available
          sudo ln -s $(pwd)/openfasttrace-3.3.1.jar /usr/local/bin/openfasttrace.jar
          echo '#!/bin/sh
          java -jar /usr/local/bin/openfasttrace.jar "$@"' | sudo tee /usr/local/bin/oft
          sudo chmod +x /usr/local/bin/oft
      
      - name: Run Traceability Analysis
        run: |
          # Import specifications from all source files and generate a tracing report
          echo "Analyzing traceability in iOS implementation..."
          oft import -i . -o trace.xml
          oft report -i trace.xml -o verification-ios.md -f markdown
      
      - uses: actions/upload-artifact@v4
        with:
          name: ios-verification
          path: verification-ios.md 